force-app/main/default/objects/Leave_Request__c/Leave_Request__c.object-meta.xml
<CustomObject>
    <label>Leave Request</label>
    <nameField>
        <label>Leave Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Request__c/fields/Duration_Category__c.field-meta.xml
<CustomField>
    <fullName>Duration_Category__c</fullName>
    <label>Duration Category</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Number_of_Days__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Days__c</fullName>
    <label>Number of Days</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LeaveRequestHandlerTest.cls
@isTest
public class LeaveRequestHandlerTest {
	@isTest
    static void testDurationCategories() {
        List<Leave_Request__c> requests = new List<Leave_Request__c>();
        
        requests.add(new Leave_Request__c(
            Name = 'Short Leave',
            Number_of_Days__c = 2
        ));

        requests.add(new Leave_Request__c(
            Name = 'Medium Leave',
            Number_of_Days__c = 4
        ));

        requests.add(new Leave_Request__c(
            Name = 'Long Leave',
            Number_of_Days__c = 7
        ));
        
        LeaveRequestHandler.calculateDurationCategory(requests);

        System.assertEquals('Short', requests[0].Duration_Category__c);
        System.assertEquals('Medium', requests[1].Duration_Category__c);
        System.assertEquals('Long', requests[2].Duration_Category__c);
        
    }
}